### ISSUE TITLE
Assert.Multiple

### ISSUE THREAD

**Issue by iperevoschikov** [skbkontur/RetryableAssertions#5]
Добавьте, пожалуйста, поддержку фичи, которая позволяет ассертить в мягком режиме. Требуется для проверки данных, когда нужно поассертить несколько полей и важно увидеть сразу все несоответствия а не исправлять их по одному на прогон теста.

**Comment by ronzhina** [comment]
@gangstatracer уточню, а вариант использовать возможности NUnit  почему не нравится? Потому что хочется ограничить по времени сразу целый скоуп проверок, а не по-отдельности каждый?
```
Assert.Multiple(() =>
    {
        // любые проверки с ожиданиями, которые быстро пройдут, если всё ок, и медленно, если не ок
        Assert.That(result.RealPart, Is.EqualTo(5.2));
        Assert.That(result, Is.EqualTo(new[] {"42"}));
        source.Items.Wait().Any(x => x.Xdeferred.Assert(Is.EqualTo("42")), Helper.AssertionConfiguration);
    });
```

**Comment by iperevoschikov** [comment]
Показалось, что Assert.Multiple не работает, но всё работает
